Add bits to try to run a second time

diff --git a/.github/workflows/run-TeXLive-action.yml b/.github/workflows/run-TeXLive-action.yml
--- a/.github/workflows/run-TeXLive-action.yml
+++ b/.github/workflows/run-TeXLive-action.yml
@@ -26,6 +26,32 @@ jobs:
           trap 'make_exit_code="$?"; echo "make_exit_code=${make_exit_code}" | tee -a "$GITHUB_OUTPUT"; if [[ "${make_exit_code}" == "2" ]]; then exit 0; fi' EXIT
           make
 
+    - name: Glue Logic testing for rerun of make/LaTeX
+      id: glue
+      run: |
+        rerun="false"
+        if [ -f thesis.log ] ; then
+          countstr=$(egrep -c -i '\sRerun to correct this|\sRerun to get citations correct|\sRerun to get cross-references right' thesis.log)
+          if [ "${{ fromJSON(steps.make-run1.outputs.make_exit_code) }}" = "2" ] ; then
+            mv -v thesis.log run1-thesis.log
+            rerun="true"
+          fi
+        fi
+        echo "rerun=${rerun}" | tee -a $GITHUB_OUTPUT
+
+    - name: Run TeXLive-Action make again
+      if: "${{ steps.glue.outputs.rerun == 'true' }}"
+      id: make-run2
+      continue-on-error: true
+      uses: xu-cheng/texlive-action@3586544d56723b23ab69aec1e9d73e7220d9c313     # v2
+      with:
+        scheme: full
+        run: |
+          # trap/capture exit codes
+          # https://github.com/orgs/community/discussions/46992#discussioncomment-9395504
+          trap 'make_exit_code="$?"; echo "make_exit_code=${make_exit_code}" | tee -a "$GITHUB_OUTPUT"; if [[ "${make_exit_code}" == "2" ]]; then exit 0; fi' EXIT
+          make
+
     - name: List
       id: list
       run: |
@@ -41,7 +67,11 @@ jobs:
         echo "::group::Set workflownamestring variable"
         printf 'workflownamestring=["%s"]\n' "${GITHUB_WORKFLOW}" | tee -a "$GITHUB_OUTPUT"
         echo "::endgroup::"
-        releasefiles='[""]'
+        if [ -e run1-thesis.log ] ; then
+          releasefiles='["run1-thesis.log"]'
+        else
+          releasefiles='[""]'
+        fi
         echo "::group::Set thesis variable"
         f="thesis.pdf"
         if [ -e ${f} ] ; then
